[variables]
NIXPACKS_PHP_ROOT_DIR = "/public"
NIXPACKS_PHP_FALLBACK_PATH = "/index.php"

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm install",
    "npm run build"
]

[phases.release]
cmds = [
    "php artisan storage:link",
    "php artisan migrate --force"
]
