[providers]
providers = ["php", "node"]

[variables]
NIXPACKS_PHP_ROOT_DIR = "/public"
NIXPACKS_PHP_FALLBACK_PATH = "/index.php"

[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs"]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm install",
    "npm run build",
    "php artisan config:clear",
    "php artisan route:clear",
    "php artisan view:clear",
    "php artisan storage:link"
]

[phases.release]
cmds = [
    "php artisan migrate --force"
]
